import Head from "next/head";
import Banner from "../Components/Banner";
import styles from "../styles/Home.module.css";

export default function Home() {
  const bannerBtnClick = () => {
    console.log("hi banner btn");
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/hme.avif" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText="View stores nearby"
          handleOnClick={bannerBtnClick}
        />
      </main>
    </div>
  );
}
