import Head from "next/head";
import Image from "next/image";
import Banner from "../Components/Banner";
import Card from "../Components/card";
import coffeeStorsData from "../data/coffee-stores.json";
import FetchCoffeeStore from "../lib/coffee-stores";
import styles from "../styles/Home.module.css";

export async function getStaticProps(context) {
  
  const coffeeStors = await FetchCoffeeStore()

  return {
    props: { coffeeStors }, // will be passed to the page component as props
  };
}

export default function Home(props) {
  const bannerBtnClick = () => {
    console.log("hi banner btn");
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images.jpg" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText="View stores nearby"
          handleOnClick={bannerBtnClick}
        />
        <div className={styles.heroImage}>
          <Image
            src="/Static/hero-image.png"
            height={400}
            width={700}
            alt="hero-image"
          />
        </div>
        {coffeeStorsData.length > 0 && (
          <>
            <h2 className={styles.heading2}>Tronto Stores</h2>
            <div className={styles.cardLayout}>
              {props.coffeeStors.map((coffeeStor) => (
                <Card
                  key={coffeeStor.fsq_id}
                  name={coffeeStor.name}
                  imgUrl={
                    coffeeStor.imgUrl ||
                    "https://images.unsplash.com/photo-1469631423273-6995642a6a40?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1203&q=80"
                  }
                  href={`/coffee-store/${coffeeStor.fsq_id}`}
                  className={styles.card}
                />
              ))}
            </div>
          </>
        )}
      </main>
    </div>
  );
}
